config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: "invitations"
  }

  root 'pages#about'

  get 'impressum',     to: 'pages#impressum'
  get 'privacy',       to: 'pages#privacy'
  get 'contact',       to: 'pages#contact'
  get 'about',         to: 'pages#about'
  get 'documentation', to: 'pages#documentation'
  get 'flashs',        to: 'pages#flashs'

  resources :seminars do
    resource  :clone, controller: 'seminars/clone', only: :create
    resources :attachments, controller: 'seminars/attachments', only: [:destroy]
  end

  namespace :admin do
    resources :settings, only: [:index, :update]
    resources :users, only: [:index, :show] do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
      resource :user_mapping, controller: 'admin_seminars/publication/user_mappings', only: :create
    end
    resources :emails, only: [:index, :show]

    resources :seminars, only: [:index, :show] do
      resource :admin_copy,  controller: 'seminars/admin_copy',  only: :create
      resource :lock,        controller: 'seminars/locks',       only: [:create, :destroy]
      collection do
        get 'search', to: 'seminars/search#search'
      end
    end

    resources :admin_seminars, only: [:index, :edit, :destroy, :update, :show] do
      resource :publication, controller: 'admin_seminars/publication', only: [:new, :create, :show]
    end

    resources :seminar_kinds, only: [:index, :new, :create, :destroy, :update]
    resources :rooms, only: [:index, :new, :create, :destroy, :update]
  end

  resource :tos, only: :show
  resource :terms_acceptance, only: :create

  resource :instructor, only: [:show, :edit, :update]
  resolve('Instructor') { :instructor }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seminar_kind.rb
# == Schema Information
#
# Table name: seminar_kinds
#
#  id          :integer          not null, primary key
#  name        :string
#  active      :boolean          default(TRUE)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class SeminarKind < ApplicationRecord
  has_many :seminars

  validates :name, uniqueness: { case_sensitive: false }

  def to_s
    name
  end
end

app/controllers/admin/seminar_kinds_controller.rb
class Admin::SeminarKindsController < NeseriController
  before_action :authenticate_user!

  def index
    @seminar_kinds = SeminarKind.all.order(active: :desc, name: :asc)
    authorize! SeminarKind.new
  end

  def new
    @seminar_kind = SeminarKind.new
    authorize!
  end

  def create
    @seminar_kind = SeminarKind.new(seminar_kind_params)
    authorize!
    if @seminar_kind.save
      flash[:success] = t('seminar_kinds.create.success')
      redirect_to admin_seminar_kinds_path
    else
      render :new
    end
  end

  def destroy
    @seminar_kind = SeminarKind.find(params[:id])
    authorize!
    @seminar_kind.update!(active: false)
    flash[:success] = t('seminar_kinds.deactivated')
    redirect_to admin_seminar_kinds_path
  end

  # reactivate
  def update
    @seminar_kind = SeminarKind.find(params[:id])
    authorize!
    @seminar_kind.toggle!(:active)
    redirect_to admin_seminar_kinds_path
  end

  private

  def seminar_kind_params
    params.require(:seminar_kind).permit(:name, :description)
  end
end

app/views/admin/seminar_kinds/_form.html.haml
= form_for [:admin, @seminar_kind], builder: BulmaFormBuilder::HorizontalBulmaFormBuilder, local: true, remote: false do |f|
  = f.errors

  = f.labeled_text_field :name, placeholder: t('seminar_kind.placeholder.name')
  = f.labeled_text_area :description, help_text: t('seminar_kind.placeholder.name')

  = f.submit

app/views/admin/seminar_kinds/index.html.haml
%h1.title= SeminarKind.model_name.human(count: 2)

%table.table.is-fullwidth
  %thead
    %tr
      %th
      %th
  %tbody
    - @seminar_kinds.each do |seminar_kind|
      - if seminar_kind.active?
        %tr
          %td= seminar_kind.name
          %td= link_to t("seminar_kind.deactivate"), admin_seminar_kind_path(seminar_kind), method: :delete
      - else
        %tr.is-selected
          %td
            = seminar_kind.name
            #{t('seminar_kind.deactivated')}
          %td= link_to t("seminar_kind.reactivate"), admin_seminar_kind_path(seminar_kind), method: :patch
    %tr
      %td.has-text-centered(colspan=2)= link_to t('seminar_kind.create'), new_admin_seminar_kind_path, class: 'button is-primary'