config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: "invitations"
  }

  root 'pages#about'

  get 'impressum',     to: 'pages#impressum'
  get 'privacy',       to: 'pages#privacy'
  get 'contact',       to: 'pages#contact'
  get 'about',         to: 'pages#about'
  get 'documentation', to: 'pages#documentation'
  get 'flashs',        to: 'pages#flashs'

  resources :seminars do
    resource  :clone, controller: 'seminars/clone', only: :create
    resources :attachments, controller: 'seminars/attachments', only: [:destroy]
  end

  namespace :admin do
    resources :settings, only: [:index, :update]
    resources :users, only: [:index, :show] do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
      resource :user_mapping, controller: 'admin_seminars/publication/user_mappings', only: :create
    end
    resources :emails, only: [:index, :show]

    resources :seminars, only: [:index, :show] do
      resource :admin_copy,  controller: 'seminars/admin_copy',  only: :create
      resource :lock,        controller: 'seminars/locks',       only: [:create, :destroy]
      collection do
        get 'search', to: 'seminars/search#search'
      end
    end

    resources :admin_seminars, only: [:index, :edit, :destroy, :update, :show] do
      resource :publication, controller: 'admin_seminars/publication', only: [:new, :create, :show]
    end

    resources :seminar_kinds, only: [:index, :new, :create, :destroy, :update]
    resources :rooms, only: [:index, :new, :create, :destroy, :update]
  end

  resource :tos, only: :show
  resource :terms_acceptance, only: :create

  resource :instructor, only: [:show, :edit, :update]
  resolve('Instructor') { :instructor }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/instructors_controller.rb
class InstructorsController < NeseriController
  before_action :authenticate_user!
  
  def show
    @instructor = current_user
    authorize! @instructor, with: InstructorPolicy
  end

  def edit
    @instructor = current_user
    authorize! @instructor, with: InstructorPolicy
  end

  def update
    @instructor = current_user
    @instructor.update instructor_params
    authorize! @instructor, with: InstructorPolicy
    if @instructor.save
      redirect_to instructor_path, notice: t(:instructor_updated)
    else
      render :edit
    end
  end

  private

  def instructor_params
    params.require(:user).permit(:firstname,
      :lastname,
      :address,
      :fax,
      :phone,
      :mobile,
      :homepage)
  end
end

app/views/instructors/edit.html.haml
%h1.title #{t(:edit_your_instructor_data)}

= form_for @instructor, url: instructor_path, builder: BulmaFormBuilder::HorizontalBulmaFormBuilder, local: true, remote: false do |f|
  = f.errors

  .box
    = f.labeled_text_field :firstname, placeholder: t('instructor.placeholder.lastname')
    = f.labeled_text_field :lastname, placeholder: t('instructor.placeholder.lastname')
    = f.labeled_text_area "address", help_text: t('instructor.helptext.address')
    = f.labeled_text_field "fax", icon: 'fa-fax'
    = f.labeled_text_field "phone", icon: 'fa-phone'
    = f.labeled_text_field "mobile", icon: 'fa-mobile'
    = f.labeled_text_field "homepage"

  = f.submit t(:save)

app/views/instructors/show.html.haml
%h1.title.has-text-centered= t(:your_instructor_data)
%h2.sub-title.has-text-centered="(#{current_user.email})"

.columns.section
  .column.is-offset-3.is-6
    %table.table.is-fullwidth
      %tbody
        - [:firstname, :lastname, :address, :fax, :phone, :mobile, :homepage].each do |attr|
          %tr
            %th= User.human_attribute_name(attr)
            %td= @instructor.send(attr)
    
    = link_to t(:edit), edit_instructor_path, class: 'button is-primary'