config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: "invitations"
  }

  root 'pages#about'

  get 'impressum',     to: 'pages#impressum'
  get 'privacy',       to: 'pages#privacy'
  get 'contact',       to: 'pages#contact'
  get 'about',         to: 'pages#about'
  get 'documentation', to: 'pages#documentation'
  get 'flashs',        to: 'pages#flashs'

  resources :seminars do
    resource  :clone, controller: 'seminars/clone', only: :create
    resources :attachments, controller: 'seminars/attachments', only: [:destroy]
  end

  namespace :admin do
    resources :settings, only: [:index, :update]
    resources :users, only: [:index, :show] do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
      resource :user_mapping, controller: 'admin_seminars/publication/user_mappings', only: :create
    end
    resources :emails, only: [:index, :show]

    resources :seminars, only: [:index, :show] do
      resource :admin_copy,  controller: 'seminars/admin_copy',  only: :create
      resource :lock,        controller: 'seminars/locks',       only: [:create, :destroy]
      collection do
        get 'search', to: 'seminars/search#search'
      end
    end

    resources :admin_seminars, only: [:index, :edit, :destroy, :update, :show] do
      resource :publication, controller: 'admin_seminars/publication', only: [:new, :create, :show]
    end

    resources :seminar_kinds, only: [:index, :new, :create, :destroy, :update]
    resources :rooms, only: [:index, :new, :create, :destroy, :update]
  end

  resource :tos, only: :show
  resource :terms_acceptance, only: :create

  resource :instructor, only: [:show, :edit, :update]
  resolve('Instructor') { :instructor }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seminar.rb
# == Schema Information
#
# Table name: seminars
#
#  id                          :integer          not null, primary key
#  title                       :string
#  subtitle                    :string
#  description                 :text
#  attendees_minimum           :integer
#  attendees_maximum           :integer
#  attendees_preconditions     :string
#  please_bring                :string
#  start_date                  :datetime
#  end_date                    :datetime
#  cancellation_time           :integer          default(7)
#  cancellation_reason         :string
#  room_material               :string
#  room_extras                 :string
#  royalty_participant         :decimal(, )
#  royalty_participant_reduced :decimal(, )
#  material_cost               :decimal(, )
#  kind                        :string           default("user")
#  uuid                        :string
#  locked                      :boolean          default(FALSE)
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  creator_id                  :integer
#  seminar_kind_id             :integer
#  accommodation               :string
#  user_seminar_id             :integer
#  alternative_dates           :text
#  other_extras                :text
#  room_wish_id                :integer
#  active                      :boolean          default(TRUE)
#  room_comment                :text
#

class Seminar < ApplicationRecord
  attr_accessor :accept_conditions

  belongs_to :creator, class_name: "User", optional: true
  belongs_to :seminar_kind, optional: true

  belongs_to :user_seminar, class_name: 'Seminar', optional: true, inverse_of: :admin_seminar, foreign_key: 'user_seminar_id'
  has_one :admin_seminar, class_name: 'Seminar', inverse_of: :user_seminar, foreign_key: 'user_seminar_id'

  belongs_to :wished_room, class_name: 'Room', optional: true, inverse_of: :seminars, foreign_key: 'room_wish_id'

  has_many :seminar_instructors, inverse_of: :seminar
  has_many :instructors, through: :seminar_instructors, class_name: "User", source: 'user'

  has_many_attached :files

  accepts_nested_attributes_for :seminar_instructors,
    reject_if: :all_blank, allow_destroy: true
  # validates_associated :seminar_instructors ?

  validates :title, presence: true

  validate :end_after_start
  validates :start_date, :end_date, presence: true

  validates :attendees_minimum, numericality: { only_integer: true, greater_than: 0, allow_nil: true }
  validates :attendees_maximum, numericality: { only_integer: true, greater_than: 0, allow_nil: true }
  validates :cancellation_time, numericality: { only_integer: true, greater_than: 0, allow_nil: true }
  validate :min_smaller_than_max

  validate :file_sizes

  validates :accept_conditions, acceptance: true, unless: :is_admin_seminar?

  scope :active, -> { where(active: true) }
  scope :future, -> { where("start_date >= ?", DateTime.now) }
  scope :past,   -> { where("start_date <= ?", DateTime.now) }
  scope :admin_copies, -> { where("user_seminar_id NOT NULL") }
  scope :user_versions, -> { where("user_seminar_id IS NULL") }
  scope :with_user, ->(user) { where(creator: user).or(self.where(seminar_instructors: user.seminar_instructors)) }

  after_initialize do |record|
    record.start_date ||= DateTime.new(DateTime.now.year + 1, 1, 20, 20, 00)
    record.end_date   ||= (record.start_date + 2.days).change({hour: 13})
  end

  def is_user_seminar?
    !user_seminar_id?
  end

  def is_admin_seminar?
    user_seminar_id?
  end

  protected

  private

  def min_smaller_than_max
    return if attendees_minimum.blank? || attendees_maximum.blank?
    
    if attendees_maximum < attendees_minimum
      errors.add(:attendees_maximum, :must_be_greater_than_minimum)
    end
  end

  def end_after_start
    return if end_date.blank? || start_date.blank?
    
    if end_date < start_date
      errors.add(:end_date, :must_be_before_start_date)
    end
  end

  def file_sizes
    if files.attached?
      files.each do |file|
        if file.blob.byte_size > 10000000
          file.purge
          errors.add(:base, :file_too_big)
        end
      end
    end
  end
end

app/controllers/admin/seminars/admin_copy_controller.rb
class Admin::Seminars::AdminCopyController < NeseriController
  before_action :authenticate_user!

  def create
    @user_seminar = Seminar.find(params[:seminar_id])
    authorize! @user_seminar, with: AdminSeminarPolicy

    if @user_seminar.admin_seminar
      helpers.add_flash t("admin.seminar.admin_copy.has_already")
      @admin_seminar = @user_seminar.admin_seminar
    elsif @user_seminar.is_admin_seminar?
      helpers.add_flash t("admin.seminar.admin_copy.is_already")
      @admin_seminar = @user_seminar
    else
      operation = AdminSeminarCloner.call(@user_seminar)
      @admin_seminar = operation.to_record
      @admin_seminar.save!
      helpers.add_flash notice: t("admin.seminar.admin_copy.created")
    end

    redirect_to edit_admin_admin_seminar_path(@admin_seminar)
  end
end

app/controllers/admin/seminars/locks_controller.rb
class Admin::Seminars::LocksController < NeseriController
  before_action :authenticate_user!

  def create
    authorize! :create?, with: LockPolicy
    if seminar.update(locked: true)
      helpers.add_flash success: t(:seminar_locked)
      redirect_back fallback_location: seminars_path
    else
      helpers.add_flash failure: t(:seminar_locked_failed)
      redirect_back fallback_location: seminars_path
    end
  end

  def destroy
    authorize! :destroy?, with: LockPolicy
    if seminar.update(locked: false)
      helpers.add_flash success: t(:seminar_unlocked)
      redirect_back fallback_location: seminars_path
    else
      helpers.add_flash failure: t(:seminar_unlock_failed)
      redirect_back fallback_location: seminars_path
    end
  end

  private

  def seminar
    Seminar.find(params[:seminar_id])
  end
end

app/controllers/admin/seminars/search_controller.rb
class Admin::Seminars::SearchController < NeseriController
  before_action :authenticate_user!

  def search
    search = SeminarSearch.new(params[:q])
    seminars = search.apply(Seminar).order(created_at: :desc)
    @pagy, @seminars = pagy(seminars,
      page_param: :current_page, items: 20)

    authorize! :index?, with: AdminPolicy
  end
end

app/controllers/admin/seminars_controller.rb
class Admin::SeminarsController < NeseriController
  before_action :authenticate_user!

  def index
    future_seminars = Seminar.user_versions.future.order(created_at: :desc)
    @pagy_current, @current_seminars = pagy(future_seminars,
      page_param: :current_page, items: 10)

    past_seminars = Seminar.user_versions.past.order(created_at: :desc)
    @pagy_past, @past_seminars = pagy(past_seminars,
      page_param: :past_page, items: 10)

    authorize!
  end

  def show
    @seminar = Seminar.find(params[:id])
    authorize! @seminar
  end

end

app/controllers/seminars/attachments_controller.rb
class Seminars::AttachmentsController < NeseriController
  before_action :authenticate_user!

  def destroy
    @attachment = ActiveStorage::Attachment.find(params[:id])
    authorize! @attachment, to: :destroy?, with: AttachmentPolicy
    @attachment.purge
    helpers.add_flash info: t('attachment.deleted')
    redirect_back fallback_location: @attachment.record
  end
end

app/controllers/seminars/clone_controller.rb
class Seminars::CloneController < NeseriController
  before_action :authenticate_user!

  def create
    @old_seminar = Seminar.find(params[:seminar_id])
    authorize! @old_seminar, with: SeminarPolicy

    if @old_seminar.is_admin_seminar?
      flash[:error] = t(:can_not_copy_admin_seminar)
      redirect_to @old_seminar
    else
      operation = SeminarCloner.call(@old_seminar, current_user: current_user)
      @seminar  = operation.to_record

      flash[:notice] = t(:copy_created)

      render 'seminars/new'
    end
  end
end

app/controllers/seminars_controller.rb
class SeminarsController < NeseriController
  before_action :authenticate_user!

  def index
    if current_user.admin?
      helpers.add_flash(hint:
        t(:admin_seminars_click_here_html,
          admin_seminars_link: admin_admin_seminars_path))
    end

    future_own_seminars = Seminar.with_user(current_user).
      user_versions.future.order(created_at: :desc)
    @pagy_current, @current_seminars = pagy(future_own_seminars,
      page_param: :current_page, items: 10)

    past_own_seminars = Seminar.with_user(current_user).
      user_versions.past.order(created_at: :desc)
    @pagy_past, @past_seminars = pagy(past_own_seminars,
      page_param: :past_page, items: 10)

    authorize!
  end

  def show
    @seminar = Seminar.find(params[:id])
    authorize! @seminar
  end

  def edit
    @seminar = Seminar.find(params[:id])
    @seminar.accept_conditions = true
    authorize! @seminar
  end

  def update
    @seminar = Seminar.find(params[:id])

    authorize! @seminar
    if @seminar.update(seminar_params)
      @seminar.seminar_instructors.find_each do |instructor|
        next if InstructorUserLink.is_correctly_linked?(instructor)
        InstructorUserLink.create_and_invite! instructor
        if !instructor.save
          helpers.add_flash error: t(:could_not_save_instructor)
        end
      end
      helpers.add_flash notice: I18n.t('seminar.saved')
      redirect_to @seminar
    else
      render :edit
    end
  end

  def new
    @seminar = Seminar.new
    authorize!
  end

  def create
    @seminar = Seminar.new(seminar_params)
    @seminar.creator = current_user
    authorize!

    if @seminar.save
      # new referees? invite them!
      @seminar.seminar_instructors.find_each do |instructor|
        next if InstructorUserLink.is_correctly_linked?(instructor)
        InstructorUserLink.create_and_invite! instructor
        if !instructor.save
          helpers.add_flash error: t(:could_not_save_instructor)
        end
      end

      redirect_to @seminar, notice: I18n.t('seminar.saved')
    else
      render :new
    end
  end

  def destroy
    @seminar = Seminar.find(params[:id])
    authorize! @seminar
    @seminar.update!(active: false)
    flash[:success] = t('seminar.pulled_back')
    redirect_to seminars_path
  end

  private

  def seminar_params
    params.require(:seminar).permit(:title, :subtitle, :description,
      :start_date, :end_date,
      :alternative_dates,
      :accommodation,
      :cancellation_time, :cancellation_reason,
      :attendees_minimum, :attendees_maximum, :attendees_preconditions, :please_bring, 
      :accept_conditions,
      :room_wish_id,
      :room_extras, :room_material, :room_comment,
      :seminar_kind_id,
      :royalty_participant, :royalty_participant_reduced, :material_cost, :honorar,
      files: [],
      seminar_instructors_attributes: [:id, :email, :main_contact, :contactable, :comment, :accommodation, :qualification, :_destroy, :lastname, :firstname, :address, :fax, :phone, :mobile, :homepage],
    )
  end
end

app/views/seminars/_form.html.haml
= form_for @seminar, builder: BulmaFormBuilder::HorizontalBulmaFormBuilder do |f|
  = f.errors

  .box
    %h2.subtitle.has-text-centered
      %span.icon
        %i.fa.fa-star
      = t('seminar.form.section.publication')
      %span.icon
        %i.fa.fa-star
    = f.labeled_text_field :title, placeholder: t('seminar.placeholder.title')
    = f.labeled_text_field :subtitle, placeholder: t('seminar.placeholder.subtitle')
    = f.labeled_text_area "description", help_text: t('seminar.helptext.description')

  .box
    %h2.subtitle.has-text-centered
      %span.icon
        %i.fa.fa-calendar
      = t('seminar.form.section.dates')
      %span.icon
        %i.fa.fa-calendar
    = f.labeled_datetime_select "start_date", help_text: t('seminar.helptext.start_date')
    = f.labeled_datetime_select "end_date", help_text: t('seminar.helptext.end_date')
    = f.labeled_collection_select "seminar_kind_id", SeminarKind.where(active: true), :id, :name
    = f.labeled_text_area "alternative_dates", icon: 'fa-calendar', help_text: t('seminar.helptext.alternative_dates')
    = f.labeled_number_field "cancellation_time", icon: 'fa-calendar', help_text: t('seminar.helptext.cancellation_time')
    = f.labeled_text_field "cancellation_reason"
  
  .box
    %h2.subtitle.has-text-centered
      %span.icon
        %i.fa.fa-users
      = t('seminar.form.section.participants')
      %span.icon
        %i.fa.fa-users
    = f.labeled_number_field "attendees_minimum", help_text: t('seminar.helptext.attendees_minimum'), icon: 'fa-window-minimize'
    = f.labeled_number_field "attendees_maximum", icon: 'fa-window-maximize'
    = f.labeled_text_field "accommodation", icon: 'fa-home', help_text: t('seminar.helptext.accommodation')
    = f.labeled_text_field "attendees_preconditions"
    = f.labeled_text_field "please_bring", icon: 'fa-suitcase'
  
  
  .box
    %h2.subtitle.has-text-centered
      %span.icon
        %i.fa.fa-sitemap
      = t('seminar.form.section.infrastructure')
      %span.icon
        %i.fa.fa-sitemap
    = f.labeled_collection_select "room_wish_id", Room.where(active: true), :id, :name
    = f.labeled_text_area "room_comment", size: 3
    = f.labeled_text_field "room_material", help_text: t('seminar.helptext.room_material'), icon: 'fa-clipboard'
    = f.labeled_text_field "room_extras", help_text: t('seminar.helptext.room_extras'), icon: 'fa-wrench'
  
  .box
    %h2.subtitle.has-text-centered
      %span.icon
        %i.fa.fa-money
      = t('seminar.form.section.costs')
      %span.icon
        %i.fa.fa-money

    .field.is-horizontal
      .field-label.is-normal
        %label.label(for="seminar_cost_participant")
          Seminarkosten für Teilnehmer*in
      .field-body
        .field.is-expanded
          %p.control.is-expanded
            %input#seminar_cost_participant.input.control.is-expanded(type="text" name="seminar[cost_participant]" value="#{(@seminar.royalty_participant.to_f/0.67)}")
          %p.help
            in Euro
        .field.is-expanded
          %p.is-expanded
            x 0.67
        .field.is-expanded
          %p.control.is-expanded
            %input#seminar_royalty_participant.input.control.is-expanded(type="text" name="seminar[royalty_participant]" readonly=true value="#{@seminar.royalty_participant}")
          %p.help
            Honorar in Euro (wird noch gerunded)
        .field-label.is-normal
          %label.label(for="seminar_royalty_participant")
            Honorar pro Teilnehmer*in
    -# Came from this markup:
    -#= f.labeled_text_field "royalty_participant", help_text: t('seminar.helptext.royalty_participant')
    :javascript
      costInputElement = document.getElementById('seminar_cost_participant');
      royaltyElement   = document.getElementById("seminar_royalty_participant");

      function setSeminarCost() {
        cost = parseFloat(costInputElement.value.replace(',','.').replace(' ',''))
        royaltyElement.value = (cost * 0.67).toFixed(2)
        //Math.round(cost * 0.67)
      }

      costInputElement.oninput = setSeminarCost

    .field.is-horizontal
      .field-label.is-normal
        %label.label(for="seminar_cost_participant_reduced")
          Ermäßigte Seminarkosten für Teilnehmer*in
      .field-body
        .field.is-expanded
          %p.control.is-expanded
            %input#seminar_cost_participant_reduced.input.control.is-expanded(type="text" name="seminar[cost_participant_reduced]" value="#{(@seminar.royalty_participant_reduced.to_f/0.67)}")
          %p.help
            für Teilnehmer*innen, die auch vom FK Sozialermäßigung erhalten. Höchstens 75% der normalen Seminarkosten.
        .field.is-expanded
          %p.is-expanded
            x 0.67
        .field.is-expanded
          %p.control.is-expanded
            %input#seminar_royalty_participant_reduced.input.control.is-expanded(type="text" name="seminar[royalty_participant_reduced]" readonly=true value="#{@seminar.royalty_participant_reduced}")
          %p.help
            Honorar in Euro (wird noch gerundet)
        .field-label.is-normal
          %label.label(for="seminar_royalty_participant_reduced")
            Honorar pro ermäßigte*m Teilnehmer*in
    -# Came from this markup
    -#= f.labeled_text_field "royalty_participant_reduced", help_text: t('seminar.helptext.royalty_participant_reduced')
    :javascript
      costReducedInputElement = document.getElementById('seminar_cost_participant_reduced');
      royaltyReducedElement   = document.getElementById("seminar_royalty_participant_reduced");

      function setSeminarCostReduced() {
        cost = parseFloat(costReducedInputElement.value.replace(',','.').replace(' ',''))
        royaltyReducedElement.value = (cost * 0.67).toFixed(2)
      }

      costReducedInputElement.oninput = setSeminarCostReduced

    = f.labeled_text_field "material_cost"
    -#= f.labeled_string "kind", default: "user"
    -#= f.labeled_string "uuid"

  .box
    %h2.subtitle.has-text-centered
      %span.icon
        %i.fa.fa-user-circle
      = t('seminar.form.section.main_referee')
      %span.icon
        %i.fa.fa-user-circle
    #instructors
      = f.fields_for :seminar_instructors do |instructor|
        = render 'seminars/seminar_instructor_fields', f: instructor
      .links
        = link_to_add_association t('seminar_instructors.add'), f, :seminar_instructors, partial: 'seminars/seminar_instructor_fields', class: 'button', wrap_object: Proc.new {|instructor| instructor.email = current_user.email; instructor }

  .box
    %h2.subtitle.has-text-centered
      %span.icon
        %i.fa.fa-file
      = t('seminar.files')
      %span.icon
        %i.fa.fa-file
    %p
      = t("seminar.files_text_html")
      %br
    %p
      %br
      %ul
        %li
          - @seminar.files.each do |file|
            = link_to file.filename, url_for(file)

      %br
      = f.file_field :files, multiple: true


  .box
    %h2.subtitle.has-text-centered
      %span.icon
        %i.fa.fa-umbrella
      = t('seminar.form.section.conditions')
      %span.icon
        %i.fa.fa-umbrella
    %p
      = t("seminar.conditions_text_html")
      %br
      %br
      .field.is-horizontal
        .field-label.is-normal
        .field-body
          .control.button.is-outlined
            = f.check_box :accept_conditions
            &nbsp;
            %b
              = f.label :accept_conditions


  .level
    .level-item-left
      = f.submit
    .level-item-right
      - if @seminar.persisted?
        = button_link_to "fa-delete", seminar_path(@seminar), t('seminar.pull_back'), 'is-danger', method: :delete

app/views/seminars/_seminar_table_row.html.haml
%tr
  %td
    - if seminar.locked?
      %span.icon
        %i.fa.fa-lock
  %td
    = link_to seminar.title, seminar
  %td
    = l(seminar.start_date, format: :short_date)
    %br
    ="-"
    %br
    = l(seminar.end_date, format: :short_date)
  %td
    = l(seminar.created_at, format: :mid)
    #{"(" + seminar.creator&.email + ")" if seminar.creator}
  %td
    - seminar.seminar_instructors.each do |instructor|
      %small
        = instructor.email
  %td
    -if seminar.locked? || seminar.is_admin_seminar? || !seminar.active? || seminar.uuid 
      .tags
        - if seminar.locked?
          %span.tag.is-warning
            =t("seminar.tags.locked")
        - if seminar.is_admin_seminar?
          %span.tag.is-info
            =t("seminar.tags.is-admin")
        - if !seminar.active?
          %span.tag.is-danger
            =t("seminar.tags.is-pulled-back")
        - if seminar.uuid
          %span.tag.is-success
            =t("seminar.tags.is-published")
    - if allowed_to? :edit?, seminar
      %p.buttons
        -# link_to_if
        = button_link_to 'fa-wrench', edit_seminar_path(seminar),  t(:edit),  'is-small is-outlined'
    - if allowed_to? :show?, seminar
      %p.buttons
        = button_link_to 'fa-clone',  seminar_clone_path(seminar), t(:clone), 'is-small is-light', method: :post
    - if allowed_to? :create?, with: AdminSeminarPolicy
      - SeminarAdminActions.new(seminar, current_user).items.each do |item|
        = button_link_to item.icon, item.url, item.title, "is-small #{item.css_classes}", method: (item.http_method || :get)
        %br

app/views/seminars/new.html.haml
%h1.title= t('seminar.new')

= render 'seminars/form'

app/views/seminars/show.html.haml
.level
  .level-item-left
    %h1.title
      = Seminar.model_name.human
      = ":"
      = @seminar.title
  .level-item-right
    - if allowed_to?(:edit?, @seminar)
      = button_link_to 'fa-edit', edit_seminar_path(@seminar), t(:edit), 'is-link'

- if @seminar.locked
  .notification.is-notice
    .media
      .media-left
        %span.icon.is-size-3
          %i.fa.fw.fa-lock
      .media-content
        = t("seminar.is-locked")

- if @seminar.admin_seminar && allowed_to?(:show?, @seminar.admin_seminar, with: AdminSeminarPolicy)
  .notification.is-link
    .media
      .media-left
        %span.icon.is-size-3
          %i.fa.fw.fa-info
      .media-content
        = t("seminar.has_admin_copy_link_html", admin_copy_path: admin_admin_seminar_path(@seminar.admin_seminar))

%br
.is-small
  - if @seminar.creator
    = Seminar.human_attribute_name(:creator).capitalize
    = @seminar.creator.email
  = l(@seminar.created_at, format: :long)
.is-small
  = Seminar.human_attribute_name(:updated_at)
  = l(@seminar.updated_at, format: :long)

%br

.columns.is-multiline
  .column.is-12
    .box
      %table.table.is-fullwidth
        %tbody
          %tr
            %th(colspan=2)
              %h2.subtitle 
                %span.icon
                  %i.fa.fa-star
                = t('seminar.form.section.publication')
          - [:title, :subtitle, :description].each do |attr|
            %tr
              %th= Seminar.human_attribute_name(attr)
              %td= @seminar.send(attr)

  .column.is-6
    %table.table.is-fullwidth.box
      %tbody
        %tr
          %th(colspan=2)
            %h2.subtitle 
              %span.icon
                %i.fa.fa-calendar
              = t('seminar.form.section.dates')
        - [:start_date, :end_date].each do |attr|
          %tr
            %th= Seminar.human_attribute_name(attr)
            %td= l(@seminar.send(attr), format: :long)
        - [:alternative_dates, :seminar_kind, :cancellation_time, :cancellation_reason].each do |attr|
          %tr
            %th= Seminar.human_attribute_name(attr)
            %td= @seminar.send(attr)
  .column.is-6
    %table.table.box.is-fullwidth
      %tbody
        %tr
          %th(colspan=2)
            %h2.subtitle 
              %span.icon
                %i.fa.fa-money
              = t('seminar.form.section.costs')
        - [:royalty_participant, :royalty_participant_reduced, :material_cost].each do |attr|
          %tr
            %th= Seminar.human_attribute_name(attr)
            %td= @seminar.send(attr)
        %tr
          %th Seminarkosten für Teilnehmer*in
          %td= (@seminar.royalty_participant.to_f / 0.67).to_i
        %tr
          %th Ermäßigte Seminarkosten für Teilnehmer*in
          %td= (@seminar.royalty_participant_reduced.to_f / 0.67).to_i
  .column.is-6
    %table.table.box.is-fullwidth
      %tbody
        %tr
          %th(colspan=2)
            %h2.subtitle 
              %span.icon
                %i.fa.fa-users
              = t('seminar.form.section.participants')
        - [:attendees_minimum, :attendees_maximum, :attendees_preconditions, :please_bring].each do |attr|
          %tr
            %td= Seminar.human_attribute_name(attr)
            %td= @seminar.send(attr)
    
  .column.is-6
    %table.table.box.is-fullwidth
      %tbody
        %tr
          %th(colspan=2)
            %h2.subtitle 
              %span.icon
                %i.fa.fa-sitemap
              = t('seminar.form.section.infrastructure')
          %tr
            %th= Seminar.human_attribute_name(:room_wish)
            %td= @seminar.wished_room&.name
        - [:room_comment, :room_material, :room_extras].each do |attr|
          %tr
            %th= Seminar.human_attribute_name(attr)
            %td= @seminar.send(attr)
    

.box
  = render 'seminars/instructors/table', seminar: @seminar

.box
  %table.table.is-fullwidth
    %tbody
      %tr
        %th(colspan=1)
          %h2.subtitle 
            %span.icon
              %i.fa.fa-file
            = t('seminar.files')
      - if @seminar.files.empty?
        %tr
          %td.is-warning= t(:none)
      - else
        %tr
          %td
            .columns.is-multiline
              - @seminar.files.each do |file|
                .column.is-2
                  = link_to file.filename, url_for(file), target: '_new'
                  - if allowed_to? :destroy?, file, with: AttachmentPolicy
                    = link_to seminar_attachment_path(@seminar, file), method: :delete do
                      %span.icon
                        %i.fa.fa-trash
                  - if file.blob.content_type.start_with? 'image'
                    = link_to url_for(file), target: '_new' do
                      = image_tag file.variant(resize: "180x100").processed
              

.box
  %h2.subtitle= t("seminar.user_actions")
  .level
    .level-item-left
      .buttons
        - navigation[:seminar_user_actions].items.each do |item|
          - method, classes = item.description.to_s.split(' ')
          - classes ||= ''
          - method ||= :get
          = button_link_to item.icon, item.url, item.title, classes, method: method
    .level-item-right
      = link_to seminar_path(@seminar), class: 'button is-danger', method: :delete do
        %span.icon.is-small
          %i.fa.fa-trash
        %span
          = t('seminar.pull_back')

- if current_user.admin?
  .box
    - if !@seminar.locked? && (allowed_to? :create?, with: LockPolicy)
      = button_link_to 'fa-lock', admin_seminar_lock_path(@seminar), t(:lock), '', method: :post
    - if @seminar.locked? && (allowed_to? :create?, with: LockPolicy)
      = button_link_to 'fa-unlock', admin_seminar_lock_path(@seminar), t(:unlock), '', method: :delete
    - if allowed_to? :create?, with: AdminSeminarPolicy
      - if @seminar.admin_seminar
        = link_to t(:view_admin_copy), admin_admin_seminar_path(@seminar), class: 'button'#, method: :post
      - else
        = link_to t(:create_admin_copy), admin_admin_seminars_path(user_seminar_id: @seminar.id), class: 'button', method: :post