config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    invitations: "invitations"
  }

  root 'pages#about'

  get 'impressum',     to: 'pages#impressum'
  get 'privacy',       to: 'pages#privacy'
  get 'contact',       to: 'pages#contact'
  get 'about',         to: 'pages#about'
  get 'documentation', to: 'pages#documentation'
  get 'flashs',        to: 'pages#flashs'

  resources :seminars do
    resource  :clone, controller: 'seminars/clone', only: :create
    resources :attachments, controller: 'seminars/attachments', only: [:destroy]
  end

  namespace :admin do
    resources :settings, only: [:index, :update]
    resources :users, only: [:index, :show] do
      post :impersonate, on: :member
      post :stop_impersonating, on: :collection
      resource :user_mapping, controller: 'admin_seminars/publication/user_mappings', only: :create
    end
    resources :emails, only: [:index, :show]

    resources :seminars, only: [:index, :show] do
      resource :admin_copy,  controller: 'seminars/admin_copy',  only: :create
      resource :lock,        controller: 'seminars/locks',       only: [:create, :destroy]
      collection do
        get 'search', to: 'seminars/search#search'
      end
    end

    resources :admin_seminars, only: [:index, :edit, :destroy, :update, :show] do
      resource :publication, controller: 'admin_seminars/publication', only: [:new, :create, :show]
    end

    resources :seminar_kinds, only: [:index, :new, :create, :destroy, :update]
    resources :rooms, only: [:index, :new, :create, :destroy, :update]
  end

  resource :tos, only: :show
  resource :terms_acceptance, only: :create

  resource :instructor, only: [:show, :edit, :update]
  resolve('Instructor') { :instructor }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  admin                  :boolean          default(FALSE)
#  firstname              :string
#  lastname               :string
#  address                :string
#  fax                    :string
#  phone                  :string
#  mobile                 :string
#  homepage               :string
#  tos_accepted_at        :date
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :integer
#  invitations_count      :integer          default(0)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :created_seminars, class_name: 'Seminar', foreign_key: 'creator_id'
  has_many :seminar_instructors, inverse_of: 'user'
  has_many :teaching_seminars, class_name: 'Seminar', foreign_key: 'seminar_id', inverse_of: 'instructors', source: 'seminar', through: :seminar_instructors

  belongs_to :instructor, required: false

  before_validation :downcase_strip_email
  before_validation :prepend_https_to_homepage

  validates_acceptance_of :tos_agreement, :allow_nil => false, on: :create

  def downcase_strip_email
    self.email = self.email.downcase.strip
  end

  def prepend_https_to_homepage
    if self.homepage.present?
      self.homepage = homepage.strip
      if !self.homepage.start_with? "http"
        self.homepage = "https://#{self.homepage}"
      end
    end
  end

  after_create :set_tos_accepted_at

  def set_tos_accepted_at
    update(tos_accepted_at: DateTime.now)
  end

  def profile_missing?
    firstname.to_s == '' || lastname.to_s == '' || address.to_s == ''
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < NeseriController
  before_action :authenticate_user!

  def index
    search = UserSearch.new(params[:q])
    admin_users = search.apply(User.all.where(admin: true).order(created_at: :desc))
    @pagy_admin, @admin_users = pagy(admin_users,
                                     page_param: :admin_users_page)

    users = search.apply(User.all.where(admin: false).order(created_at: :desc))
    @pagy, @users = pagy(users,
                         page_param: :users_page)
    authorize!
  end

  def show
    @user     = User.find(params[:id])
    @seminars = Seminar.with_user(@user)
    authorize! @user
  end

  def impersonate
    user = User.find(params[:id])
    if user == current_user
      helpers.add_flash error: t(:cannot_impersonate_self)
    end
    authorize! with: AdminPolicy
    impersonate_user(user)
    redirect_to root_path
  end

  def stop_impersonating
    stop_impersonating_user
    authorize! with: AdminPolicy
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name user
    if user&.firstname.to_s != '' || user&.lastname.to_s != ''
      "%s %s" % [user.firstname, user.lastname]
    else
      user&.email
    end
  end
end

app/views/admin/users/_user_table_row.html.haml
%tr
  %td= link_to user_name(user), admin_user_path(user)
  %td= user.email
  %td
    - user.created_seminars.each do |seminar|
      = link_to seminar.title, seminar_path(seminar)

    - user.teaching_seminars.each do |seminar|
      = link_to seminar.title, seminar_path(seminar)
  %td
    .tags
      - if user.admin
        %span.tag.is-warning
          =t("user.is-admin")
      - if user.confirmation_token && !user.confirmed_at
        %span.tag.is-warning
          =t("admin.users.tags.unconfirmed")
      - if user.invitation_token
        %span.tag.is-info
          =t("admin.users.tags.invitation_pending")
      - if user.profile_missing?
        %span.tag
          =t("admin.users.tags.profile_missing")
  %td
    -#= link_to t(:show), admin_user_path(user), class: 'button'
    %a(href="mailto:#{user.email}")
      =t(:send_mail)
    - if user != current_user
      %br
      = link_to t(:impersonate), impersonate_admin_user_path(user), method: :post

app/views/admin/users/index.html.haml
.level
  .level-item-left
    %h1.title= t(:users_index)
    %h2.subtitle (#{@pagy.count} #{User.model_name.human(count: 2)})
  .level-item
    = form_with url: admin_users_path, method: :get, local: true do |f|
      .field.has-addons
        .control
          -#.has-icons-left
          = f.text_field :q, class: 'input is-rounded', size: 6, placeholder: t('search_term'), value: params[:q]
          -#%span.icon.is-small.is-left
          -#  %i.fa.fa-search
        .control
          %button.button.is-info
            %span.icon.is-small
              %i.fa.fa-search
  .level-item-right
    - if @pagy.pages > 1
      != pagy_bulma_nav(@pagy)

%table.table.is-fullwidth
  %thead
    %tr
      %th= t("admin.users.name")
      %th= t("admin.users.email")
      %th= t("admin.users.seminars")
      %th= t("admin.users.state")
      %th= t("admin.users.actions")
  %tbody
    = render partial: 'user_table_row', collection: @users, as: 'user'
- if @pagy.pages > 1
  != pagy_bulma_nav(@pagy)

.level
  .level-item-left
    %h2.subtitle
      = t(:admin_users_index)
      (#{@pagy_admin.count})
  .level-item-right
    - if @pagy_admin.pages > 1
      != pagy_bulma_nav(@pagy_admin)
%table.table.is-fullwidth
  %thead
    %tr
      %th= t("admin.users.name")
      %th= t("admin.users.email")
      %th= t("admin.users.seminars")
      %th= t("admin.users.state")
      %th= t("admin.users.actions")
  %tbody
    = render partial: 'user_table_row', collection: @admin_users, as: 'user'
- if @pagy_admin.pages > 1
  != pagy_bulma_nav(@pagy_admin)

app/views/admin/users/show.html.haml
%h1.title= user_name @user
%h2.subtitle= @user.email

.columns.section
  .column.is-offset-3.is-6
    %table.table.is-fullwidth
      %tbody
        - [:firstname, :lastname, :address, :fax, :phone, :mobile, :homepage].each do |attr|
          %tr
            %th= User.human_attribute_name(attr)
            %td= @user.send(attr)


- if @seminars.present?
  .level
    .level-item-left
      %h2.title= t(:involved_seminars)
    .level-item-right
  = render 'seminars/seminar_table', seminars: @seminars